backend:
  name: git-gateway
  branch: main
media_folder: "_site/images/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "components"
    label: "components"
    files:
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navbar.json"
        fields:
          - { label: "brand", name: "Brand", widget: string }
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "Url", label: "url", widget: "string" }
              - { name: "Navigation", label: "navigation", widget: "string" }
          - {name: "header", label: "header", widget: "string"}
          - {name: "subheader", label: "subheader", widget: "string"}
      - name: "footer"
        label: "footer"
        file: "src/_data/footer.json"
        fields:
          - {name: "name", label: "name", widget: "string"}
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Card Heading", name: "card_heading", widget: "string"}
      - {label: "Card Subheading", name: "card_sub", widget: "string"}
      - {label: "Card Description", name: "card_desc", widget: "string"}
      - {label: "Card Image", name: "card_img", widget: "image", required: true}
  - label: "Pages"
    name: "pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/index.html"
        fields:
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/home.html",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Card Heading", name: "card_heading", widget: "string"}
          - { label: "Card Subheading", name: "card_sub", widget: "string"}
          - { label: "Card Description", name: "card_desc", widget: "string"}
          - { label: "Card Button", name: "card_btn", widget: "string"}
          - { label: "Card Image", name: "card_img", widget: "image", required: true}
          - { label: "Cta Heading", name: "cta_heading", widget: "string"}
          - { label: "Cta Subheading", name: "cta_sub", widget: "string"}
          - { label: "Cta Description", name: "cta_desc", widget: "string"}
      - name: "about"
        label: "about"
        file: "src/_data/about.json"
        fields:
          - { label: Title, name: title, widget: string, default: "About" }
          - { label: "Card Heading", name: "card_heading", widget: "string"}
          - { label: "Card Subheading", name: "card_sub", widget: "string"}
          - { label: "Card Description", name: "card_desc", widget: "string"}
          - { label: "Card Image", name: "card_img", widget: "image", required: true}
      - name: "products"
        label: "products"
        file: "src/products.html"
        fields:
          - { label: Title, name: title, widget: string, default: "Products" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/products.html",
            }
      - name: "store"
        label: "store"
        file: "src/store.html"
        fields:
          - { label: Title, name: title, widget: string, default: "Store" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/products.html",
            }
          - { label: "Card Heading", name: "card_heading", widget: "string"}
          - { label: "Card Subheading", name: "card_sub", widget: "string"}
          - { label: "Address", name:"address", widget: "string"}
          - { label: "Zip", name:"zip", widget: "string"}
          - { label: "Call Text", name:"call_text", widget: "string"}
          - { label: "Number", name:"number", widget: "string"}
          - label: "Operation hours"
            name: "operation_hours"
            widget: "list"
            fields:
              - { label: "Work Day", name: "work day", widget: "string"}
              - { label: "Hours", name: "hours", widget: "string"}


      