backend:
  name: git-gateway
  branch: main
media_folder: "_site/images/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/index.html"
        fields:
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/home.html",
            }
          - { label: Title, name: title, widget: string }
          - { label: About Text, name: about, widget: text }
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navbar.json"
        fields:
          - { label: "brand", name: "Brand", widget: string }
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "Url", label: "url", widget: "string" }
              - { name: "Navigation", label: "navigation", widget: "string" }
