backend:
  name: git-gateway
  branch: main
media_folder: "_site/images/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "components"
    label: "components"
    files:
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navbar.json"
        fields:
          - { label: "brand", name: "Brand", widget: string }
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "Url", label: "url", widget: "string" }
              - { name: "Navigation", label: "navigation", widget: "string" }
          - {name: "header", label: "header", widget: "string"}
          - {name: "subheader", label: "subheader", widget: "string"}
      - name: "footer"
        label: "footer"
        file: "src/_data/footer.json"
        fields:
          - {name: "name", label: "name", widget: "string"}
  - name: "homepage"
    label: "Homepage"
    file: "src/index.html"
    fields:
      - {
          label: Layout,
          name: "layout",
          widget: "hidden",
          default: "layouts/home.html",
        }
      - { label: Title, name: title, widget: string }
      - { name: "Card Heading", label: "card_heading", widget: "string"}
      - { name: "Card Subheading", label: "card_sub", widget: "string"}
      - { name: "Card Description", label: "card_desc", widget: "string"}
      - { name: "Card Button", label: "card_btn", widget: "string"}
      - { name: "Card Image", label: "card_img", widget: "image", required: true}

        